env:
  global:
    - CC_TEST_REPORTER_ID=e604200a31cfe7b887541cdd27feb83654de669afeeb3302e2501f79714e4377
sudo: false
language: node_js
node_js:
  - node
  - 12
  - 11
  - 10
  - 9
  - 8
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run buildx
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
